version: '3'

services:

  server:
    build:
      context: ./
    ports:
      - "8080:8080"
    container_name: server

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: client
    depends_on:
      - server